[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["c", "h", "cpp", "cc", "cxx", "hxx", "hpp"]
comment-token = "//"
indent = { tab-width = 6, unit = "\t" }
formatter = { command = "clang-format" , args = [""] }
language-servers = [ "clangd" ]
